# Re-sync the Memories mosaic from the source folder.
#
# Run this whenever new photos are dropped into the Images folder:
#   python scripts/sync_photos.py
# then rebuild + deploy. It rebuilds public/photos/memNN.jpg and src/data/photos.js
# from scratch, so added/removed photos are picked up. It only touches mem*.jpg —
# card photos, the logo, and joshua-card are left alone.

from PIL import Image, ImageOps
from math import gcd
import glob, os, re

SRC = r"C:\Users\beatr\Downloads\Chris's 19th\Images"
DST = r"C:\Users\beatr\Downloads\Voltade\chris-birthday\public\photos"
DATA = r"C:\Users\beatr\Downloads\Voltade\chris-birthday\src\data\photos.js"
MAX = 1600
IMG_EXT = ('.jpg', '.jpeg', '.png', '.heic', '.webp')  # videos (.mov/.mp4) skipped


def natkey(p):
    return [int(x) for x in re.findall(r'\d+', os.path.basename(p))]


def coprime_stride(n):
    # a stride near the middle, coprime with n → originally-adjacent shots land
    # far apart, breaking up bursts of the same scene/people
    for s in range(round(n * 0.45), n):
        if gcd(s, n) == 1:
            return s
    return 1


# wipe old mem tiles (leave card photos / logo / joshua-card untouched)
for old in glob.glob(os.path.join(DST, 'mem*.jpg')):
    os.remove(old)

files = [f for f in glob.glob(os.path.join(SRC, '*'))
         if f.lower().endswith(IMG_EXT)]
files.sort(key=natkey)

items = []
for i, f in enumerate(files, 1):
    im = ImageOps.exif_transpose(Image.open(f)).convert('RGB')
    w, h = im.size
    s = min(1.0, MAX / max(w, h))
    if s < 1.0:
        im = im.resize((round(w * s), round(h * s)), Image.LANCZOS)
    name = f'mem{i:02d}.jpg'
    im.save(os.path.join(DST, name), quality=82, optimize=True, progressive=True)
    r = im.size[1] / im.size[0]
    span = 'tall' if r >= 1.15 else ('wide' if r <= 0.7 else None)
    items.append((name, span))

n = len(items)
stride = coprime_stride(n)
order = [items[(i * stride) % n] for i in range(n)]
if order:
    order[0] = (order[0][0], 'big')  # feature tile first

lines = [
    '// ONE ENTRY PER PHOTO. Generated by scripts/sync_photos.py — re-run it after',
    '// adding photos to the Images folder. Order is shuffled so similar shots',
    "// aren't clustered. `span`: 'wide'=2col, 'tall'=2row, 'big'=2x2, omit=normal.",
    '',
    'export const photos = [',
]
for name, span in order:
    sp = f"'{span}'" if span else 'null'
    lines.append(f"  {{ src: '/photos/{name}', caption: '', span: {sp} }},")
lines.append(']')
open(DATA, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')

print(f'{n} photos synced (stride {stride}); skipped non-images')
